#!/usr/bin/env bash
# Build the drag-to-Applications disk image from the signed (and, in releases, stapled) Huddle.app:
#   Huddle-<version>-macos-arm64.dmg next to the bundle, with the brand background, the app icon
#   and an Applications alias laid out in a fixed Finder window. The image is signed and, when
#   HUDDLE_NOTARY_PROFILE is set, notarized and stapled too, so it opens without warnings.
# Tauri's own dmg bundler is not used: it runs before build-app.sh repairs the engine's symlinks
# and signs, so its image would carry the broken bundle.
# Usage: scripts/make-dmg.sh   (after scripts/build-app.sh; package-release.sh calls it)
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
BUNDLE_DIR="$ROOT/apps/desktop/src-tauri/target.nosync/release/bundle/macos"
APP="$BUNDLE_DIR/Huddle.app"
[ -d "$APP" ] || { echo "No Huddle.app at $APP — run scripts/build-app.sh first" >&2; exit 1; }
VERSION="$(python3 -c 'import json,sys; print(json.load(open(sys.argv[1]))["version"])' "$ROOT/apps/desktop/src-tauri/tauri.conf.json")"
OUT="$BUNDLE_DIR/Huddle-$VERSION-macos-arm64.dmg"
VOL="Huddle"
STAGE="$BUNDLE_DIR/dmg-stage"
# Window geometry; must match scripts/make-dmg-background.swift.
WIN_W=660; WIN_H=420; APP_X=165; APPS_X=495; ICON_Y=190

# A leftover mount of a previous run would keep dmgbuild from attaching its own image.
for v in /Volumes/"$VOL" /Volumes/"$VOL "*; do [ -d "$v" ] && hdiutil detach "$v" -force >/dev/null 2>&1 || true; done
rm -rf "$STAGE" "$BUNDLE_DIR/Huddle-rw.dmg" "$OUT"

# 1. Background (1× + 2× in one TIFF so Retina Finder picks the sharp one).
mkdir -p "$STAGE/.background"
swift "$ROOT/scripts/make-dmg-background.swift" "$ROOT/apps/desktop/src/assets/huddle-logo.svg" "$STAGE/.background" >/dev/null
tiffutil -cathidpicheck "$STAGE/.background/background.png" "$STAGE/.background/background@2x.png" -out "$STAGE/.background/background.tiff" >/dev/null 2>&1
rm -f "$STAGE/.background/background.png" "$STAGE/.background/background@2x.png"

# 2. Build the image with dmgbuild, which writes the window layout into .DS_Store itself
#    (ds_store + mac_alias). Finder's AppleScript route was used until macOS 27, where
#    `set background picture of icon view options` fails with -10006/-10000; this needs no Finder
#    at all, so a signed-in GUI session is no longer required either.
PYBIN="$ROOT/engine/.venv-dmg.nosync/bin/python"
if [ ! -x "$PYBIN" ]; then
  echo "creating the disk-image tool venv…"
  python3 -m venv "$ROOT/engine/.venv-dmg.nosync"
  "$PYBIN" -m pip install -q --upgrade pip
  "$PYBIN" -m pip install -q dmgbuild
fi
cat > "$STAGE/../dmg-settings.py" <<SETTINGS
# Generated by scripts/make-dmg.sh — geometry must match scripts/make-dmg-background.swift.
import os
app = os.environ["HUDDLE_DMG_APP"]
files = [app]
symlinks = {"Applications": "/Applications"}
badge_icon = os.path.join(app, "Contents/Resources/icon.icns")
background = os.environ["HUDDLE_DMG_BACKGROUND"]
window_rect = ((200, 200), ($WIN_W, $WIN_H))
default_view = "icon-view"
show_status_bar = False
show_tab_view = False
show_toolbar = False
show_pathbar = False
show_sidebar = False
icon_size = 128
text_size = 13
label_pos = "bottom"
icon_locations = {os.path.basename(app): ($APP_X, $ICON_Y), "Applications": ($APPS_X, $ICON_Y)}
format = "ULFO"
SETTINGS
HUDDLE_DMG_APP="$APP" HUDDLE_DMG_BACKGROUND="$STAGE/.background/background.tiff" \
  "$PYBIN" -m dmgbuild -s "$STAGE/../dmg-settings.py" -D app="$APP" "$VOL" "$OUT"
rm -rf "$STAGE" "$BUNDLE_DIR/dmg-settings.py"

# 3. Sign; notarize + staple when a notary profile is configured (the app inside is already stapled).
IDENTITY="${HUDDLE_SIGN_IDENTITY:--}"
codesign --force --sign "$IDENTITY" --timestamp "$OUT" 2>/dev/null || codesign --force --sign "$IDENTITY" "$OUT"
if [ -n "${HUDDLE_NOTARY_PROFILE:-}" ] && [ "$IDENTITY" != "-" ]; then
  echo "submitting the disk image to Apple's notary service…"
  if ! xcrun notarytool submit "$OUT" --keychain-profile "$HUDDLE_NOTARY_PROFILE" --wait 2>&1 | tee "$BUNDLE_DIR/notary-dmg.log" | grep "status: Accepted" >/dev/null; then
    ID="$(grep -m1 "id: " "$BUNDLE_DIR/notary-dmg.log" | awk '{print $2}')"
    [ -n "$ID" ] && xcrun notarytool log "$ID" --keychain-profile "$HUDDLE_NOTARY_PROFILE" || true
    echo "disk image notarization failed — see the log above" >&2; exit 1
  fi
  xcrun stapler staple "$OUT" >/dev/null
  spctl --assess --type open --context context:primary-signature -v "$OUT"
fi
echo "Disk image: $OUT ($(du -h "$OUT" | cut -f1))"
